---
# defaults file for mariadb-pi

# MariaDB server configuration file
mariadb_server_config: /etc/mysql/mariadb.conf.d/50-server.cnf

# MariaDB datadir (storage)
# NOTE: Any existing data will be moved to the new location
mariadb_datadir: /var/lib/mysql

# MariaDB bind address
mariadb_bind_address: 127.0.0.1

# MariaDB bind port
mariadb_bind_port: 3306

# Force cahnge the root passowrd
# NOTE: The root password is randomly generated and stored under /root/.my.cnf
mariadb_force_reset_root_pass: false

# List of databases to be created (default encoding: utf8mb4)
# NOTE: Changing the encoding will not chage the encoding on a existing database
# Example:
#   mariadb_databases:
#     - name: database1
#       encoding: utf8mb4
#     - name: database2
#     - name: database3
#       encoding: latin1
mariadb_databases: []

# List of users to be created (default location: localhost)
# IMPORTANT: changing the host will create another user
# mariadb_users:
#   - name: user1
#     host: localhost
#     password: S3cr3t1
#     priv: 'database1.*:ALL'
#   - name: user2
#     host: mypi.duckdns.org
#     password: S3cr3t2
#     priv: '*.*:ALL,GRANT'
#   - name: replication
#     password: S3cr3t3
#     priv: '*.*:REPLICATION CLIENT'
#   - name: user3
#     password: S3cr3t4
#     priv: 'database1.*:INSERT,UPDATE/database2.*:SELECT/database3.*:ALL'
mariadb_users: []

