---
- name: Create users
  mysql_user:
    name: '{{ item.name }}'
    host: '{{ item.host | default("localhost") }}'
    password: '{{ item.password }}'
    update_password: always
    priv: '{{ item.priv }}'
#     login_unix_socket: '{{ mariadb_socket }}'
    state: present
  when: item.name is defined and item.name and
        item.password is defined and item.password and
        item.priv is defined and item.priv
  with_items: '{{ mariadb_users }}'
