#!/usr/bin/env ansible-playbook
---
- name: Provision a Raspberry Pi
  hosts: "{{ target }}"
  become: yes

  vars_prompt:
  - name: "target"
    prompt: "Target host"
    private: no

  pre_tasks:
  - name: "Include {% if vault is defined %}{{ vault }}{% else %}{{ target }}{% endif %}.vault.yml (configuraiton variables, credentials, etc.)"
    include_vars: "{% if vault is defined %}{{ vault }}{% else %}{{ target }}{% endif %}.vault.yml"
    tags: always
  
  roles:
    - role: config-pi
      disable_wifi: true
      disable_bluetooth: true
      disable_ipv6: true
    - role: duckdns-pi


    
    

  