#!/usr/bin/env ansible-playbook
---
- name: Install and Configure UniFi Controller
  hosts: "{{ target | default('MyPi')}}"
  become: yes

  roles:
    - role: unifi-controller
      jvm_max_heap: 256M
      jvm_init_heap: 128M
