---
# tasks file for letsencrypt-pi

- name: Install CertBot dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - openssl
    - libssl-dev
    - ca-certificates
    - python
    - python-dev
    - python-virtualenv 
    - python3
    - python3-dev
    - python3-virtualenv
    - augeas-lenses
    - augeas-tools
    - libffi-dev
    - libaugeas0

- name: Copy the certbot-auto script
  copy: 
    src: certbot-auto
    dest: /usr/local/bin/certbot-auto
    mode: 0700
    backup: yes

- name: Install CertBot
  shell: /usr/local/bin/certbot-auto --install-only --non-interactive
  register: _res
  changed_when: "'The following NEW packages will be installed' in _res.stdout or \
                'Creating virtual environment' in _res.stdout or \
                'Installing Python packages' in _res.stdout or \
                'Installation succeeded' in _res.stdout"
- name: Install CertBot STDOUT
  debug: var=_res.stdout_lines

- name: Obtain a certificate and chain (in /etc/letsencrypt/live)
  shell: "/usr/local/bin/certbot-auto certonly --standalone --standalone-supported-challenges http-01 --http-01-port {{ letsencrypt_port }} --non-interactive --agree-tos --email {{ letsencrypt_email }} --domains {{ letsencrypt_fqdn }}"
  register: _res
  changed_when: "'Certificate not yet due for renewal' not in _res.stdout"
- name: Obtain a certificate and chain STDOUT
  debug: var=_res.stdout_lines

- name: Check/renew certificates twice a day (cronjob)
  cron:
    name: LetsEncrypt-Renew
    minute: "0"
    hour: "0,12"
    user: root
    job: /usr/local/bin/certbot-auto renew --quiet --no-self-upgrade
    cron_file: letsencrypt
