- name: Remove IPv6 hosts entry
  replace:
    dest: /etc/hosts
    regexp: '^.*::\d\t.+|.*IPv6.*$'
    backup: yes

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.all.disable_policy
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.default.disable_policy
    - net.ipv6.conf.eth0.disable_ipv6
    - net.ipv6.conf.eth0.disable_policy
    - net.ipv6.conf.lo.disable_ipv6
    - net.ipv6.conf.lo.disable_policy